// Centralized app state and common DOM references.
(function () {
  const refs = {
    fileInput: document.getElementById('audioInput'),
    dropZone: document.querySelector('.file-drop'),
    gapInput: document.getElementById('gapInput'),
    playlistElement: document.getElementById('playlist'),
    totalDurationElement: document.getElementById('totalDuration'),
    playAllButton: document.getElementById('playAll'),
    togglePlayButton: document.getElementById('togglePlay'),
    stopPlayButton: document.getElementById('stopPlay'),
    clearButton: document.getElementById('clearList'),
    nowPlayingLabel: document.getElementById('nowPlaying'),
    template: document.getElementById('playlistItemTemplate'),
    globalProgressBar: document.getElementById('globalProgressBar'),
    globalProgressText: document.getElementById('globalProgressText'),
    gapProgressRow: document.getElementById('gapProgressRow'),
    gapProgressBar: document.getElementById('gapProgressBar'),
    gapProgressText: document.getElementById('gapProgressText'),
    leadInput: document.getElementById('leadInput'),
    langButton: document.getElementById('langButton'),
    langMenu: document.getElementById('langMenu'),
    lockToggle: document.getElementById('lockReorder'),
    levelCheckToggle: document.getElementById('levelCheckToggle'),
    themeSwitch: document.getElementById('themeSwitch'),
    themeLabel: document.querySelector('.theme-emoji'),
    analyzePeakButton: document.getElementById('analyzePeak'),
    playPeakFromStartButton: document.getElementById('playPeakFromStart'),
    togglePeakPlayButton: document.getElementById('togglePeakPlay'),
    peakStatus: document.getElementById('peakStatus'),
    peakWaveform: document.getElementById('peakWaveform'),
  };

  const state = {
    playlist: [],
    sortable: null,
    draggedIndex: null,
    currentIndex: -1,
    gapTimer: null,
    gapInterval: null,
    leadTimer: null,
    leadInterval: null,
    gapStartTime: 0,
    gapDurationSec: 0,
    leadStartTime: 0,
    leadDurationSec: 0,
    isInGap: false,
    isInLead: false,
    currentHowl: null,
    progressTimer: null,
    hasPlayedOnce: false,
    audioCtx: null,
    peakInfo: null,
    peakStatusKey: 'peakIdle',
    peakStatusParams: undefined,
    spectrumTimer: null,
    snippetSource: null,
    analyser: null,
    snippetGain: null,
    snippetAnimation: null,
    peakDpr: window.devicePixelRatio || 1,
    peakCanvasWidth: 0,
    peakCanvasHeight: 0,
    peakSurfer: null,
    peakSurferReady: false,
    peakSurferTimeHandler: null,
    peakTargetEnd: null,
    autoLevelCheck: false,
    peakPausedAt: 0,
  };

  window.AppState = { refs, state };
})();
